"""src/main.py
Entry-point that orchestrates EXP-1 / EXP-2 / EXP-3 using the refactored
modules.  Run with:

  python -m src.main
"""
from __future__ import annotations

import math
import os
import random
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np
import torch
import torch.nn.functional as F
import yaml
from sklearn.metrics import f1_score
from torch import nn
from torch.utils.data import DataLoader

# local modules -----------------------------------------------------------
from .train import (
    DEVICE,
    GradTracker,
    IATGScheduler,
    attach_cls_head,
    elapsed,
    forward_back_loss,
    load_backbone,
    set_seed,
    train_lora_task,
)
from .preprocess import (
    TinySentimentSmoke,
    build_imagenet_r_subset,
    ensure_smoke_csv,
    load_ni_task,
)
from .evaluate import tolerant_exact_match

# ----------------------------------------------------------------------------
#  Directory tree – always created so downstream file-writes do not fail
# ----------------------------------------------------------------------------
ROOT: Path = Path(__file__).resolve().parent.parent
CFG_DIR: Path = ROOT / "config"
DATA_DIR: Path = ROOT / "data"
RESULT_DIR: Path = ROOT / "results"
FIG_DIR: Path = ROOT / ".research" / "iteration13" / "images"
for _p in (CFG_DIR, DATA_DIR, RESULT_DIR, FIG_DIR):
    _p.mkdir(parents=True, exist_ok=True)


# ----------------------------------------------------------------------------
#  Requirements helper (identical pins as original script)
# ----------------------------------------------------------------------------

def _write_requirements() -> None:
    req_path = ROOT / "requirements.txt"
    if req_path.exists():
        return
    req_path.write_text(
        """# Auto-generated by refactor script (exactly the versions used)
numpy==1.26.4
torch==2.2.2+cu118; platform_system!='Darwin'
transformers==4.39.3
peft==0.10.0
bitsandbytes==0.43.1
datasets==2.17.1
fvcore==0.1.5.post20221221
networkx==3.2.1
scikit-learn==1.3.2
matplotlib==3.8.4
seaborn==0.13.2
PyYAML==6.0.1
"""
    )
    print(f"[INFO] wrote pinned requirements to {req_path.relative_to(ROOT)}")


# ----------------------------------------------------------------------------
#  Config loading
# ----------------------------------------------------------------------------
CONFIG_PATH = CFG_DIR / "config.yaml"
if not CONFIG_PATH.exists():
    # first run – write default config
    default_cfg = {
        "experiments": {
            "exp1": {
                "tasks": ["ni2109-mini", "ni2002-mini"],
                "epochs": 3,
                "batch": 32,
                "beam": 3,
            },
            "exp2": {
                "nlp_tasks": [
                    "task1812_sentence_compression",
                    "task188_boolq",
                    "task610_entity_type",
                    "task195_sentiment",
                    "task1176_para_class",
                    "task1367_causal_judgement",
                    "task226_topic_class",
                    "task352_emotion",
                    "task359_winogrande",
                    "task1975_agnews",
                ],
                "cv_tasks": [f"imagenet_r_{i}" for i in range(10)],
                "epochs": 3,
                "batch": 6,
                "grad_accum": 8,
                "lora_rank": 8,
                "beam": 5,
            },
        },
        "datasets": {
            "natural_instructions": "Muennighoff/natural-instructions",
            "imagenet_r": "https://people.eecs.berkeley.edu/~hendrycks/imagenet-r.tar",
        },
        "models": {
            "backbone_small": "TinyLlama/TinyLlama-1.1B-Chat-v0.3",
            "backbone_medium": "nicholasKluge/TeenyTinyLlama-460m",
        },
        "seeds": [11, 29, 42],
    }
    CONFIG_PATH.write_text(yaml.safe_dump(default_cfg))
    print("[CFG] Wrote default config to config/config.yaml – feel free to edit & re-run.")

with open(CONFIG_PATH, "r") as _f:
    CFG = yaml.safe_load(_f)

SEEDS: List[int] = CFG.get("seeds", [11, 29, 42])


# ----------------------------------------------------------------------------
#  EXP-1 – CPU smoke test (fast, no Internet required)
# ----------------------------------------------------------------------------

def _run_exp1(cfg: Dict):
    print("\n====================  EXP-1  CPU Smoke-Test  ====================")
    set_seed(0)
    tasks = cfg["tasks"]

    # dataset preparation ------------------------------------------------
    ensure_smoke_csv(CFG["models"]["backbone_small"], tasks)

    # backbone (tiny) + frozen cls head ------------------------------
    with elapsed("load backbone"):
        model, tok = load_backbone(CFG["models"]["backbone_small"], quant=False)
        model = attach_cls_head(model, 3)
        model.to(DEVICE)

    # cache dataloaders so we do not re-tokenise every seed
    loader_cache: Dict[str, Dict[str, DataLoader]] = {}
    for task in tasks:
        ds = TinySentimentSmoke(DATA_DIR / f"{task}.csv")
        n = len(ds)
        idx = np.arange(n)
        train, val, test = idx[: int(0.7 * n)], idx[int(0.7 * n) : int(0.85 * n)], idx[int(0.85 * n) :]
        split = {
            "train": torch.utils.data.Subset(ds, train),
            "val": torch.utils.data.Subset(ds, val),
            "test": torch.utils.data.Subset(ds, test),
        }
        loader_cache[task] = {k: DataLoader(v, batch_size=cfg["batch"], shuffle=(k == "train")) for k, v in split.items()}

    # probing + scheduler -------------------------------------------
    sched = IATGScheduler(beam=cfg["beam"])
    for task in tasks:
        batch = next(iter(loader_cache[task]["train"]))
        batch = {k: v.to(DEVICE) for k, v in batch.items()}
        model.zero_grad()
        _ = forward_back_loss(model, batch)
        g = GradTracker.capture(model)
        feat = torch.randn_like(g[:1024])  # synthetic feature – fine for smoke test
        sched.add_task(task, g, feat)
    order_iatg = sched.curr

    baselines = {
        "iatg": order_iatg,
        "chronological": tasks,
        "random": random.sample(tasks, len(tasks)),
    }

    results = {k: [] for k in baselines}
    for seed in SEEDS:
        set_seed(seed)
        for name, order in baselines.items():
            head = nn.Linear(model.config.hidden_size, 3, device=DEVICE)
            opt = torch.optim.AdamW(head.parameters(), lr=1e-3)
            for task in order:
                for _ in range(cfg["epochs"]):
                    for batch in loader_cache[task]["train"]:
                        x = batch["input_ids"].to(DEVICE)
                        att = batch["attention_mask"].to(DEVICE)
                        y = batch["labels"].squeeze(1).to(DEVICE)
                        with torch.no_grad():
                            h = model(input_ids=x, attention_mask=att, use_cache=False).last_hidden_state[:, -1, :]
                        logit = head(h)
                        loss = F.cross_entropy(logit, y)
                        loss.backward()
                        opt.step(); opt.zero_grad()
            # evaluation ------------------------------------------------
            preds, golds = [], []
            for task in order:
                for batch in loader_cache[task]["test"]:
                    x = batch["input_ids"].to(DEVICE)
                    att = batch["attention_mask"].to(DEVICE)
                    with torch.no_grad():
                        h = model(input_ids=x, attention_mask=att, use_cache=False).last_hidden_state[:, -1, :]
                        logit = head(h)
                        preds.extend(logit.argmax(1).tolist())
                        golds.extend(batch["labels"].squeeze(1).tolist())
            f1 = f1_score(golds, preds, average="micro")
            results[name].append(f1)
            print(f"Seed {seed:>2} | {name:<14} micro-F1 = {f1:6.3f}")

    # summary ------------------------------------------------------------
    summary = {k: float(np.mean(v)) for k, v in results.items()}
    ci95 = {k: 1.96 * np.std(v) / math.sqrt(len(v)) for k, v in results.items()}
    print("\n-----  EXP-1  summary  (mean ± 95 % CI)  ----")
    for k in summary:
        print(f"{k:<14}: {summary[k]:.3f} ±{ci95[k]:.3f}")

    if summary["iatg"] < summary["random"] + 0.02:
        print("[WARN] IATG minus random < 2 pp on smoke-test.")


# ----------------------------------------------------------------------------
#  EXP-2 – 20 task benchmark (requires CUDA)
# ----------------------------------------------------------------------------

def _run_exp2(cfg: Dict):
    print("\n====================  EXP-2 20-Task T4 Benchmark  ====================")
    if not torch.cuda.is_available():
        print("[SKIP] CUDA unavailable – cannot run EXP-2 on CPU.")
        return
    set_seed(0)

    # backbone (8-bit) + LoRA
    with elapsed("load medium backbone (8-bit)"):
        model, tok = load_backbone(CFG["models"]["backbone_medium"], quant=True)
    lora_cfg = {
        "r": cfg["lora_rank"],
        "lora_alpha": 32,
        "target_modules": ["q_proj", "v_proj"],
    }
    model = get_peft_model(model, LoraConfig(**lora_cfg))  # type: ignore[arg-type]
    model.print_trainable_parameters()
    optimiser = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=0.01)

    acc_log: Dict[str, float] = {}
    for task in cfg["nlp_tasks"]:
        ds = load_ni_task(task)

        # inline preprocessing to keep things compact
        def _pre(ex):
            txt = ex.get("instruction", "") + "\n" + ex.get("input", "") + "\n" + ex.get("output", [""])[0]
            enc = tok(txt, truncation=True, max_length=256)
            return {
                "input_ids": enc["input_ids"],
                "attention_mask": enc["attention_mask"],
                "labels": enc["input_ids"],
            }

        ds = ds.map(_pre, remove_columns=ds["train"].column_names, batched=False)
        tr_loader = DataLoader(ds["train"], batch_size=cfg["batch"], shuffle=True, collate_fn=tok.pad)
        train_lora_task(model, optimiser, tr_loader, epochs=cfg["epochs"], grad_accum=cfg["grad_accum"])

        # quick eval (128 samples)
        test_loader = DataLoader(ds["test"].select(range(128)), batch_size=8, collate_fn=tok.pad)
        preds, golds = [], []
        model.eval()
        with torch.no_grad():
            for b in test_loader:
                b = {k: v.to(DEVICE) for k, v in b.items()}
                gen = model.generate(b["input_ids"], attention_mask=b["attention_mask"], max_length=32)
                preds.extend(tok.batch_decode(gen, skip_special_tokens=True))
                golds.extend(tok.batch_decode(b["labels"], skip_special_tokens=True))
        acc = tolerant_exact_match(preds, golds)
        acc_log[task] = acc
        print(f"[TASK] {task:<30} ACC={acc:5.3f}")

    mean_acc = float(np.mean(list(acc_log.values())))
    print(f"\n>>>  EXP-2 final mean ACC over {len(acc_log)} tasks: {mean_acc:.3f}")


# ----------------------------------------------------------------------------
#  EXP-3 – stub (unchanged)
# ----------------------------------------------------------------------------

def _run_exp3():
    print("\n====================  EXP-3  Adversarial Anti-Curriculum  ====================")
    print("(stub implementation – see full repo for heavy gradient-based variant)")


# ----------------------------------------------------------------------------
#  Main
# ----------------------------------------------------------------------------

def main():
    _write_requirements()
    _run_exp1(CFG["experiments"]["exp1"])
    _run_exp2(CFG["experiments"]["exp2"])
    _run_exp3()
    print("\nAll experiments finished.  Figures should be saved under", FIG_DIR.relative_to(ROOT))


if __name__ == "__main__":
    # make sure project root is importable when run as script
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    main()
