
```python
@@
-FIG_DIR: Path = ROOT / ".research" / "iteration13" / "images"
+# Updated iteration directory per build instructions
+FIG_DIR: Path = ROOT / ".research" / "iteration14" / "images"
@@
-    req_path.write_text(
-        """# Auto-generated by refactor script (exactly the versions used)
-numpy==1.26.4
-torch==2.2.2+cu118; platform_system!='Darwin'
-transformers==4.39.3
-peft==0.10.0
-bitsandbytes==0.43.1
-datasets==2.17.1
-fvcore==0.1.5.post20221221
-networkx==3.2.1
-scikit-learn==1.3.2
-matplotlib==3.8.4
-seaborn==0.13.2
-PyYAML==6.0.1
-"""
-    )
+    # Torch GPU wheels that include specific CUDA versions require an extra-index
+    # during installation.  For maximal portability we fall back to the vanilla
+    # 2.2.2 wheel which works on both CPU-only environments and GPU setups that
+    # already have system CUDA libraries available – this avoids the resolver
+    # error seen with the "+cu118" build.
+    req_path.write_text(
+        """# Auto-generated by refactor script (exactly the versions used)
+numpy==1.26.4
+torch==2.2.2
+transformers==4.39.3
+peft==0.10.0
+bitsandbytes==0.43.1
+datasets==2.17.1
+fvcore==0.1.5.post20221221
+networkx==3.2.1
+scikit-learn==1.3.2
+matplotlib==3.8.4
+seaborn==0.13.2
+PyYAML==6.0.1
+"""
+    )
```
